config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :flowers

  resources :users do
    resources :flowers
  end

  root 'users#index'

end

#         new_user_session GET    /users/sign_in(.:format)                   devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                   devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  devise/sessions#destroy
#            user_password POST   /users/password(.:format)                  devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#                          PATCH  /users/password(.:format)                  devise/passwords#update
#                          PUT    /users/password(.:format)                  devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                    devise/registrations#cancel
#        user_registration POST   /users(.:format)                           devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                   devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      devise/registrations#edit
#                          PATCH  /users(.:format)                           devise/registrations#update
#                          PUT    /users(.:format)                           devise/registrations#update
#                          DELETE /users(.:format)                           devise/registrations#destroy
#             user_flowers GET    /users/:user_id/flowers(.:format)          flowers#index
#                          POST   /users/:user_id/flowers(.:format)          flowers#create
#          new_user_flower GET    /users/:user_id/flowers/new(.:format)      flowers#new
#         edit_user_flower GET    /users/:user_id/flowers/:id/edit(.:format) flowers#edit
#              user_flower GET    /users/:user_id/flowers/:id(.:format)      flowers#show
#                          PATCH  /users/:user_id/flowers/:id(.:format)      flowers#update
#                          PUT    /users/:user_id/flowers/:id(.:format)      flowers#update
#                          DELETE /users/:user_id/flowers/:id(.:format)      flowers#destroy
#                    users GET    /users(.:format)                           users#index
#                          POST   /users(.:format)                           users#create
#                 new_user GET    /users/new(.:format)                       users#new
#                edit_user GET    /users/:id/edit(.:format)                  users#edit
#                     user GET    /users/:id(.:format)                       users#show
#                          PATCH  /users/:id(.:format)                       users#update
#                          PUT    /users/:id(.:format)                       users#update
#                          DELETE /users/:id(.:format)                       users#destroy
#                     root GET    /                                          users#index

app/models/flower.rb
class Flower < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :flowers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController

	before_action :set_flower, only: [:show, :edit, :update, :destroy]

	def index
		@flowers = Flower.all
	end

	def show
		@user = User.find(params[:user_id])

	end

	def new
		@flower = Flower.new
	end

	def edit

	end

	def create
		@flower = Flower.new(flower_params)
		@user = User.find(params[:user_id])
		@user.flowers << @flower

		if @flower.save
			redirect_to @user
		else
			render :action => :new
		end
	end

	def update
		if @flower.update(flower_params)
			redirect_to '/users/'
		else
			render :action => :edit
		end
	end

	def destroy
		@flower.destroy
		redirect_to root	
	end

	private
	def set_flower
		@flower = Flower.find(params[:id])
	end

	def flower_params
		params.require(:flower).permit(:name, :content, :description)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: :secure
	before_action :set_user, only: :show


	def index

		# begin
			# @app_url = "https://garden.vsapi01.com/api-search/by-url?url=" + params[:pic_url] + "&apikey=dae3d11e-30e7-4d1f-a153-1129af40a629"

		# 	data = HTTParty.get("https://garden.vsapi01.com/api-search/by-url?url=" + params[:pics].to_s + "&apikey=dae3d11e-30e7-4d1f-a153-1129af40a629")

		# 	puts "===================="
		# 	puts data
		# 	puts params[:pics]
		# 	puts params[:pics].to_s
		# 	puts "===================="


		# end

		@users = User.all
		@flowers = Flower.all

		if current_user
			puts "I'm logged in as #{current_user.email}"
		else
			puts "I'm not logged in"
		end

	end

	def create
	 #    puts "Dem params"
		# puts params
		redirect to: '/users'
	end

	def show
		@flowers = @user.flowers
	end

	private

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/flowers/_form.html.erb
<%= form_for @flower, url: user_flowers_path do |f| %>
	<h3>Title: <%= f.text_field :name %></h3></br>
	<h4>Image URL: <%= f.text_field :content %></h4></br>
	<h4>Description: <%= f.text_field :description %></h4></br>
	<%= f.submit %>
<% end %>

app/views/flowers/edit.html.erb
<div class="form-stuff">

	<h3>Edit your post</h3>

	<%= form_for @flower, url: user_flower_path do |f| %>
		<h3>Title: <%= f.text_field :name %></h3></br>
		<h4>Image URL: <%= f.text_field :content %></h4></br>
		<h4>Description: <%= f.text_field :description %></h4></br>
		<%= f.submit %>
	<% end %>
	
</div>

app/views/flowers/new.html.erb
<div class="form-stuff">
	<h2>Post a New Flower!</h2>

	<%= render :partial => 'form' %>
</div>

app/views/flowers/show.html.erb
<section id="show-section">
	<div id="show-div"><br>

		<h3><%= @flower.name%></h3><br>
		<img class="show-flower" src="<%= @flower.content %>">
		<img id="tape2" src="https://i127.photobucket.com/albums/p142/cy360/GA%20home%20page/tape2.png">
		<p><%= @flower.description %></p>
		<br>


		<p> <% if @user == current_user %> <%= link_to 'Delete', @flower, :method => 'delete' %> <% end %>
		<% if @user == current_user %> <%= link_to 'Edit Post', edit_user_flower_path(@user, @flower.id) %> <% end %>
		<%= link_to 'InstaFlower Home', root_path %>
		<%= link_to 'User Page', user_path(@user.id) %> </p>
	</div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaFlower: Share you favorite Flower Pictures</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Cutive+Mono|Pompiere' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<section id="header-banner">

  <p>
    <a href="/">Home</a> | 
  <% if user_signed_in? %>
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to 'Post a New Flower    ', new_user_flower_path(current_user.id)%> |
  <% end %>
  <% if user_signed_in? %>
    <a href="/users/<%= current_user.id %>">My Page</a>
  <% end %>
  </p>




  <h1><a id="home-link" href="/">instaFlower</a></h1>


</section>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
_form.html.erb

app/views/users/index.html.erb
<section id="main-wrapper">
	<section class="rw-wrapper">
		<h2 class="rw-sentence">
			<span>Where flowers bloom so does</span>
			<div class="rw-words rw-words-2">
				<span>love.</span>
				<span>happiness.</span>
				<span>hope.</span>
				<span>beauty.</span>
				<span>peace.</span>
				<span>wonder.</span>
			</div>
		</h2>
	</section>

	<br>

	<h3>Fresh Picked Flowers:</h3>
	<br>

	<ul class="lb-album">
		<% @flowers.reverse_each do |flower| %>
			<li>
				<a href="#image-<%=flower.id%>">
					<img class="main-image" src="<%= flower.content%>" alt="flower picture 1"/>
					<img id="tape3" src="https://i127.photobucket.com/albums/p142/cy360/GA%20home%20page/tape2.png">
					<span><%= flower.name %></span>
				</a>
				<div class="lb-overlay" id="image-<%=flower.id%>">
					<img src="<%= flower.content%>" alt="flower picture 1"/>
					<div>
						<h3><%= flower.name %><span>/<%=flower.name%>/</h3>
						<p><%= flower.description %></p>
						<a href="#image-<%=flower.id + 1 %>" class="lb-prev">Prev</a>
						<a href="#image-<%=flower.id - 1 %>" class="lb-next">Next</a>
						<%= link_to 'Visit Flower', user_flower_path(flower.user_id, flower.id) %><br>
					</div>
					<a href="#page" class="lb-close">x Close</a>
				</div>
			</li>	
		<% end %>
	</ul>
</section>


<br><br>

app/views/users/show.html.erb
<h2 id="profile"><%= @user.email %>'s fresh pics:</h2>

<div id="gallery-wrapper">
	
	
	<% @flowers.each do |f| %>	
	<div class="photo-div">
			<img src="<%= f.content %>">
			<h4><%= f.name%></h4>
			<img id="tape" src="https://i127.photobucket.com/albums/p142/cy360/GA%20home%20page/tape2.png">
	
			<p><%= link_to 'View Post', user_flower_path(@user, f.id) %></p>
			
	</div>
	<% end %>
</div>